stages:
  - build


build:linux:
  stage: build
  image: debian:buster
  before_script:
    - apt update && apt -y install build-essential git libgtest-dev libsdl2-dev scons
  script:
    - ./ci/build.sh
    - ./ci/test.sh
    - ./ci/package.sh
  artifacts:
    expire_in: 1 week
    paths:
      - '*.tar.bz2'
  tags:
    - docker
