stages:
  - build


build:linux:
  stage: build
  image: adambecker/psxact
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - ./ci/build.sh
    - ./ci/package.sh
  artifacts:
    paths:
      - '*.tar.bz2'
    expire_in: 1 week
  tags:
    - docker
