language: cpp

notifications:
  irc:
    channels:
      "chat.freenode.net#psxact"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - BUILD_TYPE="Unix Makefiles"
        - TARGET_OS=Linux
      sudo: require
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_TYPE=Xcode
        - TARGET_OS=OSX

before_install:
  - bash .travis.sh travis_before_install
  
script:
  - bash .travis.sh travis_script
