version: '{build}'
image: Visual Studio 2017
environment:
  BUILD_TYPE: Visual Studio 15 2017 Win64
  matrix:
  - CONFIG_TYPE: Release
build_script:
- cmd: >-
    set REPO_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,8%

    appveyor SetVariable -Name REPO_COMMIT_SHORT -Value %REPO_COMMIT_SHORT%

    appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip

    7z x SDL2-devel-2.0.5-VC.zip

    mkdir build

    cd build

    cmake .. -G"%BUILD_TYPE%" -DSDL2_PATH="C:\\projects\\psxact\\SDL2-2.0.5"

    cmake --build . --config %CONFIG_TYPE%

    mkdir ..\%REPO_COMMIT_SHORT%

    move Release\*.exe ..\%REPO_COMMIT_SHORT%\

artifacts:
- path: $(REPO_COMMIT_SHORT)\*.exe
  name: Binaries
